### ISSUE TITLE
Create Jenkins credential with pod service account token.

### ISSUE THREAD

**Issue by sanbornick** [redhat-developer/jenkins-operator#38]
When creating a containerized master a common pattern would be to use the Kubernetes cloud plugin to create dynamic runners in this same cluster and namespace. It would be nice if the token of the service account the pod is running as became a secret text credential in Jenkins so that enabling the Kubernetes cloud plugin for creating runners could be automatic.

**Comment by sanbornick** [comment]
We initially missed how to do this with JCasC. Perhaps its worth putting in the examples

```
secrets.yaml: |
  credentials:
    system:
      domainCredentials:
      - credentials:
        - string:
            description: "Kubernetes service account this Jenkins is running as"
            id: "jenkins-k8s-service-account"
            scope: GLOBAL
            secret: ${readFile:/var/run/secrets/kubernetes.io/serviceaccount/token}

```
