### ISSUE TITLE
Not able to create a Jenkins custom image using Jenkins Operator

### ISSUE THREAD

**Issue by k37y** [redhat-developer/jenkins-operator#42]
Steps to Reproduce:

1. Install Jenkins Operator
2. Create a custom Jenkins image as follows:
```
apiVersion: jenkins.io/v1alpha2
kind: JenkinsImage
metadata:
  name: foo
spec:
  from:
    name: jenkins/jenkins
    tag: lts
  plugins:
  - name: kubernetes
  to:
    registry: quay.io/<repo>
    name: jenkins-foo
    tag: latest
    secret: <push-secret>
```
3. Check the registry for the image.

Actual results:
The custom Jenkins image has not produced. The status shows Phase: ImageBuildSuccessful message.

Expected results:
The image should be pushed to the given registry.

**Comment by paulczar** [comment]
I have this same image, the pod has no logs:

```
apiVersion: jenkins.io/v1alpha2
kind: JenkinsImage
metadata:
  name: my-first-jenkins
spec:
  from:
    name: jenkins/jenkins
    tag: lts
  plugins:
  - name: kubernetes
  to:
    name: my-first-jenkins
    registry: 'image-registry.openshift-image-registry.svc:5000/custom-jenkins'
    tag: lts
```

```
$ kubectl logs my-first-jenkins-builder

```
